[project]
name = 'Tokenized-Commercial-Property-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.expense-allocation]
path = 'contracts/expense-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.tenant-management]
path = 'contracts/tenant-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
